# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:    
    - name: Running python scripts
    - id: files
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 0
    - uses: jitterbit/get-changed-files@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }} 
    - uses: actions/setup-python@v2
    - run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          echo "Do something with this ${changed_file}."
          python snowflake.py ${changed_file}
        done
