name: SnowflakeDeployment
 
on:
  push:
    branches: [ main ]
 
jobs:
  snowflake-deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Get changed files
      id: files
      uses: jitterbit/get-changed-files@v1
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Deploying Snowflake objects
      run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          python snowflake.py ${changed_file} ${{ steps.extract_branch.outputs.branch }}
        done