name: SnowflakeDeployment
 
on:
  push:
    branches: [ dev ]
 
jobs:
  snowflake-deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Get changed files
      id: files
      uses: jitterbit/get-changed-files@v1
    - name: Deploying Snowflake objects
      run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          python snowflake.py ${changed_file}
        done